#!/usr/bin/env bash
#===============================================================================
#
#  ________  ________  ________  ___  ___  ________ ___    ___ 
# |\   __  \|\   __  \|\   ____\|\  \|\  \|\  _____|\  \  /  /|
# \ \  \|\ /\ \  \|\  \ \  \___|\ \  \\\  \ \  \__/\ \  \/  / /
#  \ \   __  \ \   __  \ \_____  \ \   __  \ \   __\\ \    / / 
#   \ \  \|\  \ \  \ \  \|____|\  \ \  \ \  \ \  \_| /     \/  
#    \ \_______\ \__\ \__\____\_\  \ \__\ \__\ \__\ /  /\   \  
#     \|_______|\|__|\|__|\_________\|__|\|__|\|__|/__/ /\ __\ 
#                        \|_________|              |__|/ \|__| 
#                                                             
#-------------------------------------------------------------------------------
#$ name:bashfx-setup
#$ author:qodeninja
#$ date:
#$ semver:
#$ autobuild: 00005
#-------------------------------------------------------------------------------
#=====================================code!=====================================


echo "hello world"
echo "$BASH_SOURCE"


#curl -s -L https://git.io/fx-setup | bash -s --  --yes --debug
col_red="\x1b[38;5;9m"
col_green="\x1b[38;5;34m"
col_orange="\x1b[38;5;208m"
col_blue="\x1b[38;5;32m"
col_end="\x1b[1;0m"

opt_yes=1
opt_install=1
opt_debug=1
opt_clean=1
opt_prefix=1
opt_prefix_path=""

__logo(){
  local logo=$(sed -n '3,12 p' $BASH_SOURCE)
  printf "\n${col_blue}${logo//#/ }${col_end}\n" 1>&2;
}

while [[ $# -gt 0 ]]; do
  case $1 in
    --inst)
      opt_install=0;
      shift 
      ;;
    --clean)
      opt_clean=0;
      shift 
      ;;
    --yes)
      opt_yes=0;
      shift 
      ;;
    --debug)
      opt_debug=0;
      shift 
      ;;
    --path)
      opt_prefix=0;
      opt_prefix_path="$2";
      shift 
      shift 
      ;;
    *)
      shift 
      ;;
  esac
done



if [[ $inst_flag != true ]]; then
  __logo
  echo -en "BASHFX v3\n\n"
  echo -en "${col_orange}Warning: You opted to use BASHFX download only mode.\n"
  echo -en "If you forgot to run with --inst, you can do so again.\n"
  echo -en "Otherwise you can run the downloaded file.${col_end}\n\n"

  # countdown=100
  # while [ $countdown -gt 0 ]; do
  #   echo -ne "Continue? $countdown\033[0K\r"
  #   if read -r -t 1 -n 1; then
  #     exit 0
  #   fi
  #   : $((countdown--))
  # done

  #setup an obvious install path
  install_path="$HOME/Z_BASHFX_INSTALL/bin"
  mkdir -p "$install_path" 
  
  #check we could create it
  if [ -d $install_path ]; then

    cd $install_path;
    curl -sS -L -o "${install_path}/fx-install.sh" https://git.io/fx-install
    chmod +x "fx-install.sh"
    case ":$install_path:" in
      *":$PATH:"*) 
        : 
      ;;
      *)  
        PATH="$PATH:${install_path}"
      ;;
    esac

    fqp=$(which fx-install.sh)
    if [ -n "$fqp" -a -x "fx-install.sh" ] ; then
      alias fxi="fx-install.sh"
      alias fxicd="cd ${install_path}; ls -la"
      echo -en "-> ${col_green}Setup complete.${col_x}\n\n"
      echo -en "-> Run: ${col_blue}fx-install.sh install${col_x}\n"
    else
      echo "Error: fx-install.sh not executable\n"
    fi


  else
    echo "Error: Cant create install directory ($install_path)"
  fi
  

  exit 0

else
  echo "Install mode not enabled at this time."
fi
